### ISSUE TITLE
Definir recurso open-data a utilizar na app demo.

### ISSUE THREAD

**Issue by zrod** [javascript-br/reactjs-open-data#1]
Alguns sites:
http://dados.gov.br/
https://data.brla.gov/
http://www.governoaberto.sp.gov.br/

**Comment by rodolfobandeira** [comment]
Cotacao Dolar Americano: http://api.bcb.gov.br/dados/serie/bcdata.sgs.1/dados/ultimos/10?formato=json

Lista de Bibliotecas Publicas: http://bibliotecas.cultura.gov.br/api/space/find/?@select=id,singleUrl,name,type,shortDescription,endereco,acessibilidade,id,location,name,status,isVerified,emailPublico,telefonePublico,capacidade,horario,criterios,site&@order=name%20ASC&@type=json

**Comment by rodolfobandeira** [comment]
Previsao do tempo API Free: http://openweathermap.org/api
